name: CI Pipeline
on:
  push:
    branches:
      - master 
      - BTS-12_CICD
      
env:
        DOCKER_IMAGE: anooop/petapp:${{ github.sha }}
        MAVEN_OPTS: "-DskipTests=true"      

jobs:
  build:
    uses: AnoopMandal/DevOps/blob/BTS-12_CICD/.github/workflows/javabuild.yml
    secrets: inherit
  sonar:
     uses: ./.github/workflows/sonar.yml
     needs: build
     secrets: inherit     

  test:
    uses: ./.github/workflows/test.yml
    needs: sonar
    secrets: inherit  

  imagepush:
    uses: ./.github/workflows/imagepush.yml
    needs: test
    secrets: inherit  
